[package]
name = "rust"
version = "0.1.0"
authors = ["Logan Evans <loganpevans@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_approx_eq = "1.1.0"
rand = "0.7.3"
rand_distr = "0.3.0"
